controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

auth:
    path: /auth
    methods: ['POST']

# The app must register the SharedBundle routes to be able to use them
# See: https://github.com/symfony/symfony/discussions/49168#discussioncomment-4832140
linkweb_shared:
    resource: '@SharedBundle/config/routes.yaml'
